spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.6.8:31242/test
    username: harry
    password: rv0786nm
mybatis:
  mapper-locations: classpath:/mapper/*.xml

server:
  port: 8081
